#!/bin/bash

# fake makefile

#----------------------------------------

# take diff of original .bin file compared
# to the file that went bin->hex->bin
function chkdiff()
{
    echo "checking converted files:"
    pat=".bin.out.out"
    files=$(ls tests | grep -E $pat)
    for f in $files ; do
        len1=$(printf "%s" "$f" | wc -m)
        len2=$(printf "%s" "$pat" | wc -m)
        end=$(expr $len1 - $len2)
        f2=$(printf "%s" $f | cut -c 1-$end)".bin"
        echo "diff of $f2 and $f"
        diff -s "tests/"$f2 "tests/"$f
    done
}

#----------------------------------------

if [ "$1" = "clean" ] ; then
    rm tests/*.asm > /dev/null 2>&1
    rm tests/*.out > /dev/null 2>&1
    exit 0
fi

echo
ls tests
echo

# test converter
./conv.py 0 tests/*.bin
./conv.py 1 tests/*.bin.out

echo

# compare converted files
chkdiff

echo

# test disassembler
./lc3_dis.py tests/*.bin

echo
ls tests
echo
