#!/bin/bash

# this is the driver for the other programs

#----------------------------------------

# the locations of the externals (global)
LC3ASS="./workbench/lc3tools/lc3as"
LC3CVT="./workbench/lc3tools/lc3convert"
LC3CMP="./workbench/lcc-1.3/install/lcc"
LC3SIM="./workbench/lc3tools/lc3sim"
DIS="./scripts/lc3_dis.py"
CNV="./scripts/lc3_conv.py"
ASM="./scripts/lc3_asm.py"    # not done eventually provide a working assembler as an option: lc3_asm.py
TB="tests/binary/"
TA="tests/assembly/"

function main()
{
    # separate flag and files
    FLAG="$1"
    ARG_ARRAY=("$@")
    FILES=("${ARG_ARRAY[@]:1}")

    # check for flag and file >= 1
    if [ $# -lt 1 ] ; then
          errmsg "Error: Missing Arguments"
    fi

    # run sub programs with args
    if   [ "$FLAG" = "-a" ] ; then      # assemble
          $LC3ASS $2
    elif [ "$FLAG" = "-b0" ] ; then     # bin to obj
          $LC3CVT -b2  $2
    elif [ "$FLAG" = "-b1" ] ; then     # hex to obj
          $LC3CVT -b16 $2
    elif [ "$FLAG" = "-b2" ] ; then     # bin to hex
          $CNV 0 "${FILES[@]}"
    elif [ "$FLAG" = "-b3" ] ; then     # hex to bin
          $CNV 1 "${FILES[@]}"
    elif [ "$FLAG" = "-b4" ] ; then     # obj to bin
          $CNV 2 "${FILES[@]}"
    elif [ "$FLAG" = "-c" ] ; then      # compile
          echo "FIXME"
          $LC3CMP $2
    elif [ "$FLAG" = "-d" ] ; then      # disassemble
          $CNV 2 $2
          $DIS $2".out"
          # eventually need the symbol table to get integrated with the reversed asm code
          # probably write another script which can take the asm file and symbol table
          # it should then produce a integrated single asm file with the data and labels resybmolized
    elif  [ "$FLAG" = "-h" ] ; then     # help message
          echo; helpmsg; echo
    elif [ "$FLAG" = "-s" ] ; then  z    # simulate
          echo "Starting LC-3 Simulator"
          $LC3SIM
    elif  [ "$FLAG" = "-t" ] ; then      # test harness
          tester
    elif  [ "$FLAG" = "-tc" ] ; then     # delete
          cleaner
    else                                 # ERROR
          errmsg "Error: Unknown flag"
    fi
}

#----------------------------------------

function errmsg()
{
    echo; echo "$1"
    helpmsg
    echo
    exit 1
}

function helpmsg()
{
    echo "Usage:"
    echo "  $ ./disco -flag arguments"
    echo "Flags:"
    echo "  -a  = Assemble with lc3as"
    echo "  -b0 = Convert bin to obj with lc3convert"
    echo "  -b1 = Convert hex to obj with lc3convert"
    echo "  -b2 = Convert bin to hex with lc3_conv.py"
    echo "  -b3 = Convert hex to bin with lc3_conv.py"
    echo "  -b4 = Convert obj to bin with lc3_conv.py"
    echo "  -c  = Compile with lcc"                     # not done?
    echo "  -d  = Disassemble with lc3_dis.py"
    echo "  -h  = Display this help message"
    echo "  -s  = Simulate with lc3-sim"                # not done?
    echo "  -t  = Test"
}

# take diff of an original file compared to the converted
# takes 3 arguments for file extentions to match
# 1. directory of files
# 2. extention for converted file,
# 3. extention for original file
function chkdiff()
{
    echo "checking converted files:"
    files=$(ls $1 | grep -E $2)
    for file in $files ; do
        len1=$(printf "%s" "$file" | wc -m)
        len2=$(printf "%s" "$2" | wc -m)
        end=$(expr $len1 - $len2)
        file2=$(printf "%s" "$file" | cut -c 1-$end)"$3"
        echo "diff of $file2 and $file"
        diff -s "$1$file2"  "$1$file"
        echo
    done
}

function cleaner()
{
    echo; echo "cleaner"; echo

    rm $TB*.asm > /dev/null 2>&1
    rm $TB*.hex > /dev/null 2>&1
    rm $TB*.obj > /dev/null 2>&1
    rm $TB*.out > /dev/null 2>&1

    rm $TA*.obj > /dev/null 2>&1
    rm $TA*.sym > /dev/null 2>&1
    rm $TA*.out > /dev/null 2>&1
    rm $TA*.out.asm > /dev/null 2>&1
}

# tests that the file format converter and disassembler work
function tester()
{
    # bin->hex to hex->bin
    # bin->hex to hex->obj to obj->bin
    # hex->bin to bin->obj to obj->bin to bin->hex

    echo
    echo "converter"; echo                  # test converter
    $CNV  0  $TB*.bin                       # bin to hex
    $CNV  1  $TB*.bin.out                   # hex to bin
    echo
    chkdiff  $TB  .bin.out.out  .bin        # compare converted files
    echo
    $DIS  $TB*.bin                          # test disassembler
    echo

    # eventually collect all assemblable files into the assembly folder
    # then can only loop through the good ones and assemble then disassemble and compare
    echo "assessemble disassemble"; echo    # test assemble and disassemble
    for file in $(ls $TA)
    do
        echo; echo "assessemble $file"; echo
        $LC3ASS "$TA$file"
        echo; echo "disassemble $file"; echo
        BOOM=${file%.*} # remove .asm from file name
        $CNV 2 "$TA$BOOM".obj
        $DIS "$TA$BOOM".obj.out
    done

    echo
}

#----------------------------------------

# call main function and pass command line arguments
main $@

