#!/bin/bash

# fake makefile/test harness

#----------------------------------------

# take diff of an original file compared to the converted
# takes 2 "arguments" for file extentions to match
# 1. pat = extention for converted file,
# 2. suf = extention for original file
# yes I realize I could use $1 and $2 as args, but this is more readable

pat=""
suf=""
function chkdiff()
{
    echo "checking converted files:"
    files=$(ls tests | grep -E $pat)
    for f in $files ; do
        len1=$(printf "%s" "$f" | wc -m)
        len2=$(printf "%s" "$pat" | wc -m)
        end=$(expr $len1 - $len2)
        f2=$(printf "%s" $f | cut -c 1-$end)$suf
        echo "diff of $f2 and $f"
        diff -s "tests/"$f2 "tests/"$f
    done
}

#----------------------------------------

if [ "$1" = "-clean" ] ; then
    rm tests/*.asm > /dev/null 2>&1
    rm tests/*.out > /dev/null 2>&1
    exit 0
fi

echo
ls tests
echo

# test converter
./lc3_conv.py 0 tests/*.bin
./lc3_conv.py 1 tests/*.bin.out

echo

# compare converted files
pat=".bin.out.out"
suf=".bin"
chkdiff

echo

# test disassembler
./lc3_dis.py tests/*.bin

echo
ls tests
echo
